import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { REF_BLOCK_SIZE, RUNTIME_KEY, RUNTIME_VERSION } from './src/contract.ts';

const packages = new URL('../', import.meta.url);
const check = process.argv.includes('--check');
const expectedBun = '1.3.14';
if (Bun.version !== expectedBun) throw new Error(`Build the runtime with Bun ${expectedBun}; found ${Bun.version}`);
const build = await Bun.build({
  entrypoints: [fileURLToPath(new URL('src/install.ts', import.meta.url))],
  root: fileURLToPath(new URL('.', import.meta.url)),
  target: 'browser',
  format: 'iife',
  minify: false,
  sourcemap: 'none',
});
if (!build.success || build.outputs.length !== 1) throw new AggregateError(build.logs, 'Runtime build failed');
const source = await build.outputs[0]!.text();
const manifest =
  JSON.stringify(
    {
      version: RUNTIME_VERSION,
      key: RUNTIME_KEY,
      refBlockSize: REF_BLOCK_SIZE,
      sha256: createHash('sha256').update(source).digest('hex'),
      bundler: `bun@${expectedBun}`,
    },
    null,
    2,
  ) + '\n';
const outputs = new Map<string, string>();
const fuseLicense = await readFile(new URL('node_modules/fuse.js/LICENSE', import.meta.url), 'utf8');
const thirdPartyLicenses =
  'Fuse.js 7.5.0\nCopyright (c) 2026 Kiro Risk\nhttps://github.com/krisk/Fuse\n\n' + fuseLicense;
for (const directory of ['claude-toolsets-js/src/generated', 'claude-toolsets-python/e2b_claude_toolsets/_runtime']) {
  outputs.set(`${directory}/runtime.js`, source);
  outputs.set(`${directory}/manifest.json`, manifest);
  outputs.set(`${directory}/THIRD_PARTY_LICENSES.txt`, thirdPartyLicenses);
}
outputs.set(
  'claude-toolsets-js/src/generated/runtime-contract.ts',
  '// Generated by packages/claude-toolsets-runtime/build.ts. Do not edit.\n' +
    (await readFile(new URL('src/contract.ts', import.meta.url), 'utf8')),
);
for (const [path, content] of outputs) {
  const url = new URL(path, packages);
  if (check) {
    const actual = await readFile(url, 'utf8').catch(() => undefined);
    if (actual !== content) throw new Error(`${path} is stale; run pnpm build:runtime`);
  } else {
    await mkdir(new URL('.', url), { recursive: true });
    await writeFile(url, content);
  }
}
console.log(check ? 'Runtime assets match the source.' : 'Built runtime assets for TypeScript and Python.');
